server:
  port: 8787

spring:
  datasource:
    url: jdbc:h2:mem:carddb
    username: ricardo
    password: zaragoza
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console